version: "3.8"

services:
  reverse-proxy:
    image: nginx:latest
    restart: always
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - purchases
      - classroom
      - redis
    volumes:
      - ./packages/config/nginx.conf:/etc/nginx/nginx.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"

  purchases:
    image: postgres:14
    container_name: purchases-db
    restart: always
    environment:
      - POSTGRES_DB=purchases
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - PGPORT=5433
    volumes:
      - purchases_data:/var/lib/postgresql/data
    ports:
      - "5433:5433"

  classroom:
    image: postgres:14
    container_name: classroom-db
    restart: always
    environment:
      - POSTGRES_DB=classroom
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - PGPORT=5434
    volumes:
      - classroom_data:/var/lib/postgresql/data
    ports:
      - "5434:5434"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka_ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  redis:
    image: redis:6
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  purchases_data:
    driver: local
  
  classroom_data:
    driver: local
