version: "3.8"

services:
  reverse-proxy:
    image: nginx:latest
    restart: always
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - postgres
      - redis
    volumes:
      - ./packages/config/nginx.conf:/etc/nginx/nginx.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  db_data:
